/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryIdRouteImport } from './routes/services.$categoryId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryIdRoute = ServicesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ServicesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prices': typeof PricesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prices': typeof PricesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prices': typeof PricesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prices'
    | '/services'
    | '/admin/deposits'
    | '/admin/login'
    | '/api/chat'
    | '/services/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prices'
    | '/services'
    | '/admin/deposits'
    | '/admin/login'
    | '/api/chat'
    | '/services/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/prices'
    | '/services'
    | '/admin/deposits'
    | '/admin/login'
    | '/api/chat'
    | '/services/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricesRoute: typeof PricesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$categoryId': {
      id: '/services/$categoryId'
      path: '/$categoryId'
      fullPath: '/services/$categoryId'
      preLoaderRoute: typeof ServicesCategoryIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryIdRoute: typeof ServicesCategoryIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryIdRoute: ServicesCategoryIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricesRoute: PricesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
